### ISSUE TITLE
Remove key settings from the top-level

### ISSUE THREAD

**Issue by Ambrevar** [agzam/exwm-edit#15]
As mentioned here: https://github.com/ch11ng/exwm/issues/708#issuecomment-587416861,
you should remove the key bindings from the top-level.
I suggest you add those bindings as a suggestion in the README.

**Comment by chasecaleb** [comment]
You can disable it by setting `exwm-edit-bind-default-keys` to nil, fortunately:
https://github.com/agzam/exwm-edit/blob/bc25ba094b383be3c650ca0b7e1534efe2bb154f/exwm-edit.el#L241-L243

**Comment by Ambrevar** [comment]
Indeed, a mode map is the right way to go I believe.  Also the `exwm-edit-bind-default-keys` is missing from the README.
