### ISSUE TITLE
exwm-edit remembers past edit history when entering blank editing fields & a related security question.

### ISSUE THREAD

**Issue by axd-v** [agzam/exwm-edit#2]
Hello, I am happy beyond words to discover your package. Thank you from the bottom of my heart for creating this, as silly as that may sound.

I've encountered an issue on my system (guixSD, emacs 26.1, spacemacs latest devel, exwm 0.18) wherein if a field that I want to edit in e.g. firefox has no text, then upon invoking `exwm-edit--compose` through a shortcut, exwm-edit will show the old text that was copied into its buffer for editing whenever `exwm-edit--compose` was last ran on a different text-entry field. It doesn't show the changes that you made to the particular contents of the last text-field, only the original text that was yanked upon `exwm-edit--compose`. I think that this is undesirable behavior given that the expectation is that I'll be presented with an empty buffer and all of the contents that I add to it, upon `exwm-edit--finish` command, will be added to the text field with no other text from previous edits.

This issue also raises a concern as to what information and where exwm-edit stores. If one were to, for example, edit a password entry field using exwm-edit (obviously there is not much editing that passwords usually require), should they be worried about their password being stored in cache or plain text file somewhere? With the issue I described it would seem that there is some history going on and it could be a security problem for more sensetive types of data. Would you say that exwm-edit is safe to use for editing every kind of data and if not will it ever be?

Once again, thank you for your magnificent work, other than these small concerns I am ecstatic to have emacs help guide my computing in yet another form.

**Comment by agzam** [comment]
Thank you for your kind words and I apologize for that it took me so long to respond. exwm-edit doesn't actually store anything - it uses whatever is in the Emacs's kill-ring. I am aware of the issue you describing, but unfortunately I have no idea at this point how to fix it. I hope to be able to fix it soon, since it is occasionally annoys me too. It seems to be erratic and I'm having trouble reproducing it with consistency - otherwise I probably would've found out what's causing this bug.

**Comment by agzam** [comment]
I think I have fixed it in https://github.com/agzam/exwm-edit/commit/6ea0a64e47d06204d826e146c3c3082dec5c4007 Also now it automatically recognizes if anything is pre-selected and won't try to select all (before you'd have to pass a universal argument to prevent it from selecting all).
