### ISSUE TITLE
Please restore previous window layout when done

### ISSUE THREAD

**Issue by DamienCassou** [agzam/exwm-edit#6]
When I press `C-c C-c`  after I'm done typing my text, the content correctly goes to the original window but this one incorrectly takes the whole workspace now. How to reproduce:

1. split your workspace/frame into 2 windows, one containing Firefox, this other one containing the scratch buffer
2. in Firefox, type `C-c '` to start exwm-edit
3. Validate your content with `C-c C-c`

Expected: I see the scratch buffer and Firefox
Actual: I only see Firefox

**Comment by agzam** [comment]
I think this is fixed now. Set `exwm-edit-split` and it should work.
